-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('PR_RETURNED', 'PR_APPROVED', 'PR_REJECTED', 'PR_RECEIVED', 'PR_PAID', 'APPROVAL_PENDING', 'RECEIVING_PENDING', 'RISK_FLAG_NEW', 'OTHER') NOT NULL;
